spring:
  mvc:
    async:
      request-timeout: -1
    static-path-pattern: /storage/**
  web:
    resources:
      static-locations: file:${phi.storage.local.base-dir}
      add-mappings: on
  application:
    name: material
  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:${DB_FILE:app.db}
    name: "phi-material"
  security:
    csrf: ${CSRF_ENABLE:on}
    user:
      name: test
      password: 123456
    oauth2:
      client:
        registration:
          github:
            client-id: Ov23liT2qfXbByb1kPSL
            client-secret: ${SECRET}
            scope:
              - read:user
              - read:email
  servlet:
    multipart:
      max-file-size: 1GB
      max-request-size: 1GB
phi:
  storage:
    choose: local
    local:
      base-dir: ${LOCAL_BASE_DIR:./store}
  ffmpeg:
    cmd-path: ${FFMPEG_PATH:ffmpeg}

springdoc:
  api-docs:
    path: "/manager/v3/api-docs"
  webjars:
    prefix: "/manager/webjars"
  swagger-ui:
    path: "/manager/swagger-ui.html"
    config-url: "/manager/v3/api-docs/swagger-config"
    url: "/manager/v3/api-docs"
    oauth:
      client-id: ${spring.security.oauth2.client.registration.github.client-id}
      client-secret: ${spring.security.oauth2.client.registration.github.client-secret}
  show-login-endpoint: on

logging:
  level:
    org.springframework.security: info
    com.phi.material.dao: info
    com.phi.auth.dao: info

management:
  endpoints:
    web:
      exposure:
        include: "*"

debug: off