spring:
  application:
    name: material
  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:${DB_FILE:app.db}
    name: "phi-material"
  security:
    user:
      name: test
      password: 123456
    oauth2:
      client:
        registration:
          github:
            client-id: Ov23liT2qfXbByb1kPSL
            client-secret: ${SECRET}
            scope:
              - read:user
              - read:email

springdoc:
  api-docs:
    path: "/manager/v3/api-docs"
  webjars:
    prefix: "/manager/webjars"
  swagger-ui:
    path: "/manager/swagger-ui.html"
    config-url: "/manager/v3/api-docs/swagger-config"
    url: "/manager/v3/api-docs"
  show-login-endpoint: on

logging:
  level:
    org.springframework.security: debug

management:
  endpoints:
    web:
      exposure:
        include: "*"

debug: off
server:
  servlet:
    session:
      tracking-modes: cookie