spring:
  mvc:
    async:
      request-timeout: -1
  application:
    name: material
  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:${DB_FILE:app.db}
    name: "phi-material"
  security:
    csrf: ${CSRF_ENABLE:off}
    user:
      name: test
      password: 123456
    oauth2:
      client:
        registration:
          github:
            client-id: Ov23liT2qfXbByb1kPSL
            client-secret: ${SECRET:8f665beb9f075d16b4169b623448a5eb5a496b00}
            scope:
              - read:user
              - read:email
  servlet:
    multipart:
      max-file-size: 1GB
      max-request-size: 1GB
phi:
  ui:
    base-dir: ${UI_BASE_DIR:./ui/}
    path-pattern: ${UI_PATH:/ui/**}
  storage:
    choose: local
    local:
      base-dir: ${LOCAL_BASE_DIR:./store/}
      path-pattern: ${STORAGE_PATH:/storage/**}
  ffmpeg:
    cmd-ffmpeg: ${FFMPEG_PATH:ffmpeg}
    cmd-ffprobe: ${FFMPEG_PATH:ffprobe}

springdoc:
  api-docs:
    path: "/manager/v3/api-docs"
  webjars:
    prefix: "/manager/webjars"
  swagger-ui:
    path: "/manager/swagger-ui.html"
    config-url: "/manager/v3/api-docs/swagger-config"
    url: "/manager/v3/api-docs"
    oauth:
      client-id: ${spring.security.oauth2.client.registration.github.client-id}
      client-secret: ${spring.security.oauth2.client.registration.github.client-secret}
  show-login-endpoint: on

logging:
  level:
    org.springframework.security: info
    com.phi.material.dao: info
    com.phi.auth.dao: info

management:
  endpoints:
    web:
      exposure:
        include: "*"

debug: off